config/routes.rb
Rails.application.routes.draw do
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :teams
  resources :team_associations
  resources :integrations

  root  'passthrough#index'
  match '/home', to: 'static_pages#home', via:'get'
  match '/dashboard',  to: 'static_pages#dashboard', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/restore',  to: 'users#restore',            via: 'get'
  match '/update_account',  to: 'users#edit',            via: 'get'
  match '/restore_account',  to: 'users#restore_account',            via: 'post'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController 
    
    def home
    end

    def dashboard
    	@user = current_user
        @team = active_team
        @teams = current_user.teams.all
    	respond_to do |format|
    		format.html
    		format.json
    		format.js
    	end
    end
    
end

app/views/static_pages/dashboard.html.erb
<% provide(:title, "My Dashboard") %>
<% content_for :nav do %>
	<%= render partial: "shared/team_nav/nav_bar"  %>
<% end %>
<h1>My Dashboard</h1>

<li class="btn">
	<%= link_to signout_path,  method: "delete" do %>
        <i class="fa fa-sign-out"></i>
        <span>Log Out</span>
    <% end %>
</li>


<% @teams.each do |t| %>
	<div class="well">
    	<h1><%= t.name %></h1>
    	<%= link_to "Go", team_path(t), class: "btn btn-primary" %>
 	</div>
<%end%>

app/views/static_pages/home.html.erb
<% provide(:title, "Welcome to Swag!") %>

<div class="row">
  <div class="col-md-4 col-md-offset-4">
  <legend class="centered"><h1>Welcome to Swag!</h1></legend>
     <div class="well">
     <%= link_to "Sign up", signup_path, :class=>"btn btn-primary btn-lg btn-block"%>
     <%= link_to "Login", signin_path, :class=>"btn btn-primary btn-lg btn-block"%>
    </div>
  </div>
</div>