config/routes.rb
Rails.application.routes.draw do
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :teams
  resources :team_associations
  resources :integrations

  root  'passthrough#index'
  match '/home', to: 'static_pages#home', via:'get'
  match '/dashboard',  to: 'static_pages#dashboard', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/restore',  to: 'users#restore',            via: 'get'
  match '/update_account',  to: 'users#edit',            via: 'get'
  match '/restore_account',  to: 'users#restore_account',            via: 'post'

end

app/views/shared/team_nav/_menu_button.html.erb
<div class="menu-button" toggle-off-canvas="">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
</div>

app/views/shared/team_nav/_nav_bar.html.erb
<section id="header" class="top-header">
	<header class="clearfix ng-scope">

    <!-- Team Logo -->
    <%= render partial: 'shared/team_nav/team_logo'%>
  	
  	<div class="top-nav">
	    <!-- Side Menu Trigger Bars-->
	    <%= render partial: 'shared/team_nav/menu_button'%>
	 
	 	<!-- Current User Dropdown Links -->
	    <%= render partial: 'shared/team_nav/user_links'%>

	    <!-- Float Right Links -->
	    <%= render partial: 'shared/team_nav/right_links'%>
	</div>

	</header>
</section>

<!-- Current User Dropdown Links -->
<%= render partial: 'shared/team_nav/side_menu'%>

app/views/shared/team_nav/_right_links.html.erb
<ul class="nav-right pull-right list-unstyled">
    <li class="dropdown">
        <a href="" class="dropdown-toggle bg-orange" data-toggle="dropdown">
            <i class="fa fa-gear"></i>
        </a>
        <ul class="dropdown-menu pull-right dropdown-light with-arrow">
            <li>
                <%= link_to edit_team_path(@team) do %>
                    <i class="fa fa-pencil"></i>
                    <span>Team settings</span>
                <% end %>
            </li>
        </ul>
    </li>
</ul>

app/views/shared/team_nav/_side_menu.html.erb
<aside id="nav-container">
	<div id="nav-wrapper">
    	<ul id="nav">
        	<li>
        		<%=link_to dashboard_path do %> 
        			<i class="fa fa-dashboard"></i><span>Dashboard</span> 
        		<%end%>
        	</li>
        </ul>
    </div>
</aside>

app/views/shared/team_nav/_team_logo.html.erb
<div class="logo">
    <%= link_to team_path(@team) do %>
        <span class=""><%= @team.name %></span>
    <%end%>
</div>

app/views/shared/team_nav/_user_links.html.erb
<ul class="nav-left list-unstyled">
    <li>
        <a href="#/" data-toggle-min-nav="" class="toggle-min"><i class="fa fa-bars"></i></a>
    </li>
    <li class="dropdown">
		<a href="" class="dropdown-toggle" data-toggle="dropdown">
			<span class="hidden-xs">
                <span><%= @user.name %></span>
            </span>
            <span class="caret"></span>
		</a>
        <ul class="dropdown-menu dropdown-dark with-arrow">
            <li>
                <%= link_to edit_user_path(current_user) do %>
                    <i class="fa fa-pencil"></i>
                    <span>Edit Profile</span>
                <% end %>
            </li>
            <li>
                <a href="#/tasks">
                    <i class="fa fa-check"></i>
                    <span data-i18n="My Tasks">My Tasks</span>
                </a>
            </li>
            <li>
                <a href="#/pages/lock-screen">
                    <i class="fa fa-lock"></i>
                    <span data-i18n="Lock">Lock</span>
                </a>
            </li>
            <li>
            	<%= link_to signout_path,  method: "delete" do %>
                    <i class="fa fa-sign-out"></i>
                    <span>Log Out</span>
                <% end %>
            </li>
        </ul>
    </li>
</ul> 