config/routes.rb
Rails.application.routes.draw do
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :teams
  resources :team_associations
  resources :integrations

  root  'passthrough#index'
  match '/home', to: 'static_pages#home', via:'get'
  match '/dashboard',  to: 'static_pages#dashboard', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/restore',  to: 'users#restore',            via: 'get'
  match '/update_account',  to: 'users#edit',            via: 'get'
  match '/restore_account',  to: 'users#restore_account',            via: 'post'

end

app/views/shared/user_registration/_header.html.erb
<legend class="centered">
  <h1><%= page_header(yield(:header)) %></h1>
  <p class="lead"><%= page_lead(yield(:lead)) %></p>
</legend>

app/views/shared/user_registration/_team_form.html.erb
<div class="form-container">
    <section>
         <%= form_for @team,  :html => {:class => "form", :role => "form-horizontal"} do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
            <div class="form-group input-group-lg">
              <%= f.text_field :name, :placeholder => "Team Name", :class => "form-control"  %>
            </div>

             <div class="form-group input-group-lg">
              <%= f.text_area :description, :placeholder => "Description of your team", :class => "form-control"  %>
            </div>

            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <%= f.submit "Create team", :class => "btn btn-primary btn-block" %>
                </div>  
              </div>
              <div class="col-md-6"
                <div class="form-group">
                    <%= link_to "Cancel", teams_path, :class => "btn btn-default btn-block" %>  
                </div>
              </div>

            </div>

        <%end%>
    </section>
     <section>
        <p class="text-center text-muted">Don't overthink it. You can always edit it later.</p>
    </section>
</div>

app/views/shared/user_registration/_user_form.html.erb
<div class="form-container">
    <section>
         <%= form_for @user,  :html => {:class => "form", :role => "form-horizontal"} do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
            <div class="form-group input-group-lg">
                <%= f.text_field :name, :placeholder => "Name", :class => "form-control" %>
            </div>

            <div class="form-group input-group-lg">
                <%= f.text_field :email, :placeholder => "Email", :class => "form-control"   %>
            </div>
            <div class="form-group input-group-lg">
                <%= f.password_field :password, :placeholder => "Password", :class => "form-control"  %>
            </div>
            <div class="form-group input-group-lg">
                <%= f.password_field :password_confirmation, :placeholder => "Confirm Password", :class => "form-control"   %>
            </div>

            <div class="form-group">
              <%= f.submit "Sign up", :class => "btn btn-primary btn-block btn-lg" %>  
            </div>

        <%end%>
    </section>

    <section>
        <p class="text-center text-muted">Already have an account? <%=link_to "Log in now", signin_path %></p>
    </section>

</div>

 